Coin Machine Learning Algorithm Practice
***

### Simple Example

In [225]:
import numpy as np
train_feature  = np.array([[10], [8], [5], [3], [1]])  # 공부시간
# 2차원 array로 만든 이유
# 현재는 feature를 단순화 하기위해 1가지 변수(공부시간)만 들어가 있지만, 
# 실제로는 여러 가지 feature들이 들어갈 수 있기 때문에 2차원으로 만들어준다.
# 1차원 index = i 번째 데이터에 접근, 2차원 index = i번째 feature에 접근
train_label_regression = np.array([100, 80, 50, 30, 10]) # 성적
train_label_binary_classification = np.array([1, 1, 1, 0, 0]) # Pass/Non Pass
train_label_multi_classification = np.array([1, 2, 3, 0, 0]) # A,B,C,F,F

#### numpy 쓰는 이유

In [3]:
# python list 사용
[1,2,3] * [1,2,3] # Error

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
# np 사용
# 연산이 편리함
np.array([1,2,3])*np.array([1,2,3])

array([1, 4, 9])

### Linear Regression

In [7]:
import random
# data
x_train = train_feature
y_train = train_label_regression
x_test = np.array([[6]])

W = random.uniform(0,20)

size = len(x_train)
cost = 0
gradient = 0
learning_rate = 0.01

#### GradientDescentOptimizer

In [8]:
for cnt in range(20):
    for i in range(size):
        hypothesis = W*x_train[i]
        cost += np.square(hypothesis-y_train[i]) # 차이값 제곱해서 더하기
        gradient += (hypothesis - y_train[i])*x_train[i]
    cost = cost/size #  평균구하기
    gradient = gradient/size
    descent = W - learning_rate * gradient
#     if cnt % 10 == 0 :
    print(f'cnt={cnt:2d}, cost={float(cost):10.4f}, descent= {float(descent):.5f}')
    W = descent

cnt= 0, cost= 2841.7191, descent= 15.08681
cnt= 1, cost= 1598.1942, descent= 12.38965
cnt= 2, cost=  546.9141, descent= 10.89914
cnt= 3, cost=  141.5591, descent= 10.24318
cnt= 4, cost=   30.6654, descent= 10.01520
cnt= 5, cost=    6.1423, descent= 9.96356
cnt= 6, cost=    1.2813, descent= 9.96773
cnt= 7, cost=    0.2977, descent= 9.98141
cnt= 8, cost=    0.0733, descent= 9.99154
cnt= 9, cost=    0.0175, descent= 9.99694
cnt=10, cost=    0.0039, descent= 9.99923
cnt=11, cost=    0.0008, descent= 10.00000
cnt=12, cost=    0.0002, descent= 10.00015
cnt=13, cost=    0.0000, descent= 10.00012
cnt=14, cost=    0.0000, descent= 10.00007
cnt=15, cost=    0.0000, descent= 10.00003
cnt=16, cost=    0.0000, descent= 10.00001
cnt=17, cost=    0.0000, descent= 10.00000
cnt=18, cost=    0.0000, descent= 10.00000
cnt=19, cost=    0.0000, descent= 10.00000


#### prediction

In [9]:
# 예측이라는 것은 결국 잘 학습된 모델()
prediction = W * x_test # 공부시간이 6시간일 때 점수 예측
prediction

array([[59.99999629]])

#### Multi variable Linear Regression

In [181]:
# (x1+x2)/2 = y 인 식에 대한 linear Regerssion
x_train = np.array([[100,90], [80, 90], [45, 55], [30, 20], [10, 0]])
y_train = np.array([[95], [85], [50], [25], [5]])
size = x_train.shape[0]
W = np.array([random.uniform(0,1),random.uniform(0,1)])
learning_rate = 5e-5

print("----------------------------------------------")
for cnt in range(2000):
    hypothesis = W*x_train
    cost = np.mean(np.square(np.sum(hypothesis, axis=1).reshape(size,1)-y_train)) # 차이값 제곱해서 더하기
    gradient = np.mean((np.sum(hypothesis, axis=1).reshape(size,1)-y_train)*x_train, axis=0)
    W = W - learning_rate * gradient
    if cnt % 200 == 0:
        print(f'cnt={cnt:2d}, cost={float(cost):10.4f}')
        print(f'w1 = {float(W[0]):.3f}, w2= {float(W[1]):.3f}')
        print("----------------------------------------------")

----------------------------------------------
cnt= 0, cost=  172.1209
w1 = 0.894, w2= 0.232
----------------------------------------------
cnt=200, cost=    4.0492
w1 = 0.701, w2= 0.300
----------------------------------------------
cnt=400, cost=    1.4893
w1 = 0.622, w2= 0.379
----------------------------------------------
cnt=600, cost=    0.5478
w1 = 0.574, w2= 0.426
----------------------------------------------
cnt=800, cost=    0.2015
w1 = 0.545, w2= 0.455
----------------------------------------------
cnt=1000, cost=    0.0741
w1 = 0.527, w2= 0.473
----------------------------------------------
cnt=1200, cost=    0.0273
w1 = 0.517, w2= 0.484
----------------------------------------------
cnt=1400, cost=    0.0100
w1 = 0.510, w2= 0.490
----------------------------------------------
cnt=1600, cost=    0.0037
w1 = 0.506, w2= 0.494
----------------------------------------------
cnt=1800, cost=    0.0014
w1 = 0.504, w2= 0.496
----------------------------------------------


In [193]:
x_test = np.array([[10,50]])
prediction = np.sum(W*x_test)
print(f'pridiction = {prediction:.3f}')

pridiction = 29.911


#### using sklearn

In [194]:
from sklearn import linear_model
lr_model = linear_model.LinearRegression()
lr_model.fit(x_train, y_train)
lr_model.coef_

array([[0.5, 0.5]])

In [202]:
# 우리가 만든 모델의 테스트 데이터 사용
# x_test = np.array([[10,50]])
lr_model.predict(x_test)

array([[30.]])

### Logistic Regression
- linear regression 모델을 logistic function을 통해서 binarry classification으로 변경시켜줌

In [228]:
x_train = train_feature
y_train = train_label_binary_classification
x_test = np.array([[3]])

logistic_regression_model = linear_model.LogisticRegression()
logistic_regression_model.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [229]:
for i in range(1,10):
    prediction = logistic_regression_model.predict(np.array([[i]]))
    result = "합격" if prediction == 1 else '불합격'
    print(f'{i}시간 공부시 합격여부 = {result}')

1시간 공부시 합격여부 = 불합격
2시간 공부시 합격여부 = 합격
3시간 공부시 합격여부 = 합격
4시간 공부시 합격여부 = 합격
5시간 공부시 합격여부 = 합격
6시간 공부시 합격여부 = 합격
7시간 공부시 합격여부 = 합격
8시간 공부시 합격여부 = 합격
9시간 공부시 합격여부 = 합격


### kNN(k - Nearest Neighbors)
- k개의 인접한 점의 분류 결과를 보고 새로운 점의 분류 결과를 예측함

In [230]:
x_train = np.array([
    [9, 2], # kick count, kiss count
    [8, 4], # kick count, kiss count
    [5, 0], # kick count, kiss count
    [4, 0], # kick count, kiss count
    [5, 2], # kick count, kiss count
    [2, 7], # kick count, kiss count
    [4, 8], # kick count, kiss count
    [3, 9], # kick count, kiss count
    [0, 9], # kick count, kiss count
    [1, 6], # kick count, kiss count
])
# y_train = np.array([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])
y_train = np.array([1,1,1,1,1,0,0,0,0,0])

In [241]:
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier(n_neighbors=3) # n_neighbors를 통해 k값을 조절 가능
clf.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [242]:
for i in range(1,10):
    kick_count = random.uniform(1,9)
    kiss_count = random.uniform(1,9)
    prediction = clf.predict(np.array([[kick_count, kiss_count]]))
    result = "액션영화" if prediction == 1 else '로맨스영화'
    print('----------------------------------------------------------------')
    print(f'kick = {kick_count:.0f}, kiss = {kiss_count:.0f}일 때 예측결과 = {result}')
print('----------------------------------------------------------------')

----------------------------------------------------------------
kick = 1, kiss = 9일 때 예측결과 = 로맨스영화
----------------------------------------------------------------
kick = 5, kiss = 4일 때 예측결과 = 액션영화
----------------------------------------------------------------
kick = 6, kiss = 8일 때 예측결과 = 로맨스영화
----------------------------------------------------------------
kick = 4, kiss = 3일 때 예측결과 = 액션영화
----------------------------------------------------------------
kick = 6, kiss = 7일 때 예측결과 = 로맨스영화
----------------------------------------------------------------
kick = 7, kiss = 6일 때 예측결과 = 액션영화
----------------------------------------------------------------
kick = 2, kiss = 5일 때 예측결과 = 로맨스영화
----------------------------------------------------------------
kick = 2, kiss = 8일 때 예측결과 = 로맨스영화
----------------------------------------------------------------
kick = 5, kiss = 6일 때 예측결과 = 로맨스영화
----------------------------------------------------------------


### Decision Tree(의사 결정 나무)
- 트리 구조의 분류기를 만들어서 분류

In [244]:
from sklearn import tree
x_train = train_feature
y_train = train_label_multi_classification
clf = tree.DecisionTreeClassifier()
clf.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [251]:
for i in range(1,15):
    prediction = clf.predict(np.array([[i]]))
    result = chr(prediction+64) if prediction != 0 else 'F'
    print(f'{i:2d}시간 공부시 학점 예측 = {result}')

 1시간 공부시 학점 예측 = F
 2시간 공부시 학점 예측 = F
 3시간 공부시 학점 예측 = F
 4시간 공부시 학점 예측 = F
 5시간 공부시 학점 예측 = C
 6시간 공부시 학점 예측 = C
 7시간 공부시 학점 예측 = B
 8시간 공부시 학점 예측 = B
 9시간 공부시 학점 예측 = B
10시간 공부시 학점 예측 = A
11시간 공부시 학점 예측 = A
12시간 공부시 학점 예측 = A
13시간 공부시 학점 예측 = A
14시간 공부시 학점 예측 = A


##  (과제) 위 구현된 모델을 참고하여 아래의 3가지 모델에 대해서 자신이 간단히 조사하여<br>markdown을 작성하고 간단한 예제를 활용하여 예측 모델 구현
 - sklearn 공식 홈페이지 (https://scikit-learn.org/stable/index.html)
 - 데이터 셋은 자유롭게 가져오거나 본인이 창작하여 사용

### Random Forest

### Naive Bayes algorithm

### SVM(Support Vector Meachine)